
lovelace:
  dashboards:
    lovelace-casa:
      mode: yaml
      title: Casa
      icon: mdi:home-heart
      show_in_sidebar: true
      filename: dashboards/casa.yaml

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
  logs:
    micloud: debug
    miio: debug
    homeassistant.components.xiaomi_miio: debug

sensor:
  - platform: rest
    name: IP Pubblico
    resource: https://api.ipify.org
    value_template: "{{ value }}"
    scan_interval: 1800

template:
  - binary_sensor:
      - name: "Connessione Internet"
        device_class: connectivity
        state: "{{ states('sensor.ip_pubblico') not in ['unknown', 'unavailable', 'none', ''] }}"
